# TARDIS_MODEL

---

> **Auteur**: Laurince AGANI    
> **Dataset**: `cleaned_dataset.csv`    
> **Objectif**: Prédire le retard moyen à l'arrivée de tous les trains (`Average delay of all trains at arrival`) en minutes, et comprendre les causes des dysfonctionnements opérationnels.

---

### Plan du notebook    
1. Importation des librairies nécessaires et configurations 
2. Chargement et inspection des données

## 1. Importation des librairies nécessaires et configurations

In [7]:
# Manipulation de données
import numpy as np
import pandas as pd

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn: Préprocessing
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

# Utilitaires
import warnings
warnings.filterwarnings("ignore")

## 2. Chargement et inspection des données

In [4]:
# Chargement du dataset
df = pd.read_csv(
    "cleaned_dataset.csv",
    sep=';',
    encoding="utf-8"
)

# Inspection initiale du dataset
print('=' * 84)
print("APERÇU DES 5 PREMIÈRES LIGNES")
print('=' * 84)
display(df.head(5))

# Forme du dataser
print("Dimensions du dataset")
print(f"    {df.shape[0]} observations")
print(f"    {df.shape[1]} features")

====================================================================================
APERÇU DES 5 PREMIÈRES LIGNES
====================================================================================

      Date   Service  ... is_delayed Cancellation_rate
0  2018-01  National  ...          1          0.005747
1  2018-01  National  ...          1          0.002463
2  2018-01  National  ...          0          0.000000
3  2018-01  National  ...          1          0.005906
4  2018-01  National  ...          0          0.008475

[5 rows x 28 columns]

Dimensions du dataset
    11487 observations
    28 features

In [ ]:
# Informations sur le dataset
print('=' * 84)
print("INFORMATIONS SUR LE DATASET")
print('=' * 84)
df.info()

====================================================================================
INFORMATIONS SUR LE DATASET
====================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 11487 entries, 0 to 11486
Data columns (total 28 columns):
 #   Column                                                                         Non-Null Count  Dtype
---  ------                                                                         --------------  -----
 0   Date                                                                           11487 non-null  str
 1   Service                                                                        11487 non-null  str
 2   Departure station                                                              11487 non-null  str
 3   Arrival station                                                                11487 non-null  str
 4   Average journey time                                                           11487 non-null  float64
 5   Number of scheduled trains                                                     11487 non-null  float64
 6   Number of cancelled trains                                                     11487 non-null  float64
 7   Number of trains delayed at departure                                          11487 non-null  float64
 8   Average delay of late trains at departure                                      11487 non-null  float64
 9   Average delay of all trains at departure                                       11487 non-null  float64
 10  Number of trains delayed at arrival                                            11487 non-null  float64
 11  Average delay of late trains at arrival                                        11487 non-null  float64
 12  Average delay of all trains at arrival                                         11487 non-null  float64
 13  Number of trains delayed > 15min                                               11487 non-null  float64
 14  Average delay of trains > 15min (if competing with flights)                    11487 non-null  float64
 15  Number of trains delayed > 30min                                               11487 non-null  float64
 16  Number of trains delayed > 60min                                               11487 non-null  float64
 17  Pct delay due to external causes                                               11487 non-null  float64
 18  Pct delay due to infrastructure                                                11487 non-null  float64
 19  Pct delay due to traffic management                                            11487 non-null  float64
 20  Pct delay due to rolling stock                                                 11487 non-null  float64
 21  Pct delay due to station management and equipment reuse                        11487 non-null  float64
 22  Pct delay due to passenger handling (crowding, disabled persons, connections)  11487 non-null  float64
 23  Year                                                                           11487 non-null  int64
 24  Month                                                                          11487 non-null  int64
 25  Delay categories                                                               11487 non-null  str
 26  is_delayed                                                                     11487 non-null  int64
 27  Cancellation_rate                                                              11477 non-null  float64
dtypes: float64(20), int64(3), str(5)
memory usage: 2.5 MB

In [9]:
# Statistiques descriptives du dataset
print('=' * 84)
print("STATISTIQUES DESCRIPTIVES DU DATASET")
print('=' * 84)
df.describe().round(2)

====================================================================================
STATISTIQUES DESCRIPTIVES DU DATASET
====================================================================================

       Average journey time  ...  Cancellation_rate
count              11487.00  ...           11477.00
mean                 170.72  ...                inf
std                   87.16  ...                NaN
min                    0.00  ...               0.00
25%                  101.00  ...               0.00
50%                  164.00  ...               0.01
75%                  222.00  ...               0.03
max                  786.00  ...                inf

[8 rows x 23 columns]

In [13]:
# Analyse des valeurs manquantes

# Afficher les colonnes avec des valeurs manquantes
missing = df.isnull().sum()
missing_pct = ((df.isnull().sum() * 100) / len(df))

missing_df = pd.DataFrame({
    "Valeurs manquantes": missing,
    "Pourcentage (%)": missing_pct.round(2)
}).sort_values("Pourcentage (%)", ascending=False)

missing_with_nan = missing_df[missing_df["Valeurs manquantes"] > 0]

print('=' * 84)
print("VALEURS MANQUANTES PAR COLONNE")
print('=' * 84)
if len(missing_with_nan) == 0:
    print("Aucune valeur manquante détectée !")
else:
    display(missing_with_nan)
    print(f"{len(missing_with_nan)} colonnes contiennent des valeurs manquantes.")

====================================================================================
VALEURS MANQUANTES PAR COLONNE
====================================================================================

                   Valeurs manquantes  Pourcentage (%)
Cancellation_rate                  10             0.09

1 colonnes contiennent des valeurs manquantes.